swagger: "2.0"
info:
  description: "Locator back service"
  version: "1.0.0"
  title: "Locator"
  termsOfService: ""
  contact:
    email: "zeen@zeen.ru"
host: "locator.com"
basePath: "/"
schemes:
- "https"
paths:
  /lang/getText/{lang}:
    get:
      tags:
      - "lang"
      summary: "Получение всех текстов по заданному языку"
      description: ""
      operationId: "getText"
      produces:
      - "application/json"
      parameters:
      - name: "lang"
        in: "path"
        description: ""
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid Lang supplied"
        "404":
          description: "Lang not found"
  /lang/getLang:
    get:
      tags:
      - "lang"
      summary: "Получение всех языков"
      description: ""
      operationId: "lang"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Lang"
          
definitions:
  Lang:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  Translate:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      ident :
        type: "string"
        format: "string"
      text :
        type: "string"
        format: "string"
      langId:
        type: "integer"
        format: "int64"
      deleted:
        type: "boolean"
        default: false       
